eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8773

spring:
  application:
    name: zipkin03
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1

feign:
  hystrix:
    enabled: false
